### PR TITLE
fix(network): filter multiaddr before seeding Kademlia

### LINKED ISSUE #84: Loopback Addresses Advertised via Kademlia
### Description

When nodes bind to `0.0.0.0` or `127.0.0.1`, they currently advertise loopback or private addresses via **Kademlia** (through the Identify → DHT integration in `process_identify_event`). Other peers then attempt to dial those non-routable addresses, which can cause them to accidentally connect to themselves. This results in:

* `WrongPeerId` errors, and/or
* `Dial error: no addresses for peer` failures when peers share the same listening port (e.g., all using UDP 9090).

This behavior mainly affects remote or multi-host deployments, where local addresses cannot be routed between nodes.
In local development setups (e.g., single-host), advertising loopback or private addresses is *desirable* — so the fix must account for that.

### Symptoms

* Peers show up correctly in Kademlia’s DHT but cannot establish direct connections.
* `WrongPeerId` errors in swarm logs:
    * `Dial error: Unexpected peer ID PeerA at /ip4/127.0.0.1/udp/9090`
    * `Dial error: no addresses for peer`
* Using unique ports per peer (e.g., 9090, 9091, 9092) mitigates the issue temporarily.
* Connections via relays or gateways succeed, while direct ones fail.

### Root Cause

In the Kademlia integration code, specifically in:

```rust
fn process_identify_event(&mut self, event: identify::Event) {
    match event {
        identify::Event::Received { peer_id, info, .. } => {
            for addr in info.listen_addrs {
                self.swarm()
                    .behaviour_mut()
                    .kademlia()
                    .add_address(&peer_id, addr);
            }
        }
        ...
    }
}
```

All addresses announced by a peer (including local, loopback, and private) are added directly to the DHT.

Peers subsequently attempt to dial these addresses even if they are **non-routable** in their network environment.
When multiple peers share the same port, dialing a `/127.0.0.1:<port>` entry causes self-dialing — the local listener responds, and the peer receives its own ID back (`WrongPeerId`).

####  1. Add configurable address filtering

Introduce a configuration mechanism that allows filtering of **loopback** and **private** IP addresses before adding them to Kademlia.
Filtering should default to **enabled** for production but remain **configurable** for local testing.

Example configuration:

```toml
[network]
filter_loopback = true     # Default: true
filter_private = true      # Default: true
```

* **Default (recommended for production):**
  Loopback (`127.0.0.0/8`) and private networks (`10.0.0.0/8`, `172.16.0.0/12`, `192.168.0.0/16`) are filtered.
* **For local development:**
  Developers can disable filtering to allow full loopback and LAN-based peer discovery.

#### 2. Filter addresses in `process_identify_event`

Wrap the existing loop:

```rust
for addr in info.listen_addrs {
    self.swarm()
        .behaviour_mut()
        .kademlia()
        .add_address(&peer_id, addr);
}
```

with address filtering logic:

```rust
for addr in info.listen_addrs.into_iter().filter(|addr| filter_multiaddr(addr, &config)) {
    self.swarm()
        .behaviour_mut()
        .kademlia()
        .add_address(&peer_id, addr);
}
```

Add a helper such as:

```rust
fn filter_multiaddr(addr: &Multiaddr, cfg: &NetworkConfig) -> bool {
    if cfg.filter_loopback && is_loopback(addr) {
        return false;
    }
    if cfg.filter_private && is_private(addr) {
        return false;
    }
    true
}
```

The `is_loopback` and `is_private` utilities can parse `Multiaddr` using `multiaddr::Protocol::Ip4`/`Ip6` and compare against known CIDRs.

#### 3. Apply consistently across all binaries

The same configuration and filtering logic should apply across:

* Scheduler
* Worker
* Gateway
* Any other libp2p-based components

Gateways may choose to keep filtering disabled (since they advertise external addresses), but the option should still be available for consistency.

### PR DESCRIPTION
**Pull request by orlandohohmeier**
Nodes were leaking loopback and RFC1918 listen addrs into the DHT via Identify -> Kademlia, causing peers to redial themselves and hit `WrongPeerId`/`no addresses for peer` Errors. The network crate now provides a mechanism to exclude any reported multiaddr that falls inside a configurable set of CIDR blocks before adding it to Kademlia.

A default exclusion list (loopback, private, link-local, IPv6 ULA) is provided by `reserved_cidrs()`, re-exported alongside `IpNet`. Gateway, scheduler, and worker configs/CLIs can override it with repeated `exclude_cidr` entries.

Fixes #84

### CODE REVIEW

File: crates/network/src/lib.rs [hunk 1]
```diff
@@ -45,5 +45,52 @@ pub mod stream;
...
+    vec![
+        IpNet::from_str("127.0.0.0/8").expect("valid CIDR"),
+        IpNet::from_str("::1/128").expect("valid CIDR"),
+    ]
+}
+
+/// Private IPv4 CIDRs (RFC1918).
+pub fn private_cidrs() -> Vec<IpNet> {
+    vec![
+        IpNet::from_str("10.0.0.0/8").expect("alid CIDR"),
```
Comment (l45k) [inline crates/network/src/lib.rs]:
```suggestion
        IpNet::from_str("10.0.0.0/8").expect("valid CIDR"),
```
?

Comment (orlandohohmeier) [reply crates/network/src/lib.rs]: Fixed.

**Review by nfnt — APPROVED** [review]
LGTM!
